-- create
CREATE TABLE KPOP_GROUPS (
  empId INTEGER PRIMARY KEY,
  NAME VARCHAR(50),
  MEMBERS INTEGER,
  DEBUT INTEGER,
  "GROUP STATUS" VARCHAR(50)
);

-- insert
INSERT INTO KPOP_GROUPS VALUES (001, 'BTS', 7, 2013, 'active');
INSERT INTO KPOP_GROUPS VALUES (002, 'TWICE', 9, 2015, 'active');
INSERT INTO KPOP_GROUPS VALUES (003, 'GFRIEND', 6, 2015, 'disbanded');
INSERT INTO KPOP_GROUPS VALUES (004, 'LE SSERAFIM', 5, 2022, 'active');
INSERT INTO KPOP_GROUPS VALUES (005, 'TOMORROW BY TOGETHER', 5, 2019, 'active');

INSERT INTO KPOP_GROUPS VALUES (006, 'IZONE', 12, 2018, 'disbanded');
INSERT INTO KPOP_GROUPS VALUES (007, 'EXO', 9, 2012, 'semi-active');
INSERT INTO KPOP_GROUPS VALUES (008, 'WANNA ONE', 11, 2019, 'disbanded');
INSERT INTO KPOP_GROUPS VALUES (009, 'MAMAMOO', 4, 2014, 'semi-active');
INSERT INTO KPOP_GROUPS VALUES (010, 'HEARTS2HEARTS', 8, 2025, 'active');

INSERT INTO KPOP_GROUPS VALUES (011, 'ILLIT', 5, 2024, 'active');
INSERT INTO KPOP_GROUPS VALUES (012, 'CLC', 7, 2015, 'indefinite hiatus');
INSERT INTO KPOP_GROUPS VALUES (013, 'CORTIS', 5, 2025, 'active');
INSERT INTO KPOP_GROUPS VALUES (014, 'SEVENTEEN', 13, 2015, 'active');
INSERT INTO KPOP_GROUPS VALUES (015, 'BOYNEXTDOOR', 6, 2023, 'active');

-- fetch 

-- 1. Find all the listed disbanded kpop groups
SELECT NAME FROM KPOP_GROUPS
WHERE "GROUP STATUS" = 'disbanded';

-- 2. List all active kpop groups
SELECT NAME FROM KPOP_GROUPS
WHERE "GROUP STATUS" = 'active';

-- 3. All active groups that debuted during 2013-2015
SELECT NAME, DEBUT 
FROM KPOP_GROUPS
WHERE "GROUP STATUS" = 'active' AND DEBUT BETWEEN 2013 AND 2022
ORDER BY DEBUT DESC